# Generated by Django 3.1.7 on 2021-02-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='* Eks: BMW I3 2009, Airbus A319', max_length=120, null=True)),
                ('mode_of_transport', models.CharField(help_text='* Eks: Car, Plane', max_length=30, null=True)),
                ('engine', models.FloatField(blank=True, help_text='Engine size in liter', null=True)),
                ('fuel', models.CharField(blank=True, help_text='Eks: Electric, Diesel', max_length=120, null=True)),
                ('drag', models.FloatField(blank=True, help_text='Newtons', null=True)),
                ('climate', models.CharField(blank=True, choices=[('Tropical', 'Tropical'), ('Dry', 'Dry'),
                                                                  ('Temperate', 'Temperate'),
                                                                  ('Continental', 'Continental'), ('Polar', 'Polar')],
                                             max_length=120, null=True)),
                ('weight', models.IntegerField(blank=True, help_text='Kg', null=True)),
                ('passengers', models.IntegerField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
