# Generated by Django 3.1.7 on 2021-02-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20210225_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
